export const userData = [{
        name: 'Jan',
        "Active User": 4000,
    },
    {
        name: 'Fab',
        "Active User": 3000,

    },
    {
        name: 'Mar',
        "Active User": 1000,

    },
    {
        name: 'Apr',
        "Active User": 2780,
    },
    {
        name: 'May',
        "Active User": 3450,
    },
    {
        name: 'Jun',
        "Active User": 2190,
    },
    {
        name: 'Agu',
        "Active User": 3230,
    },
    {
        name: 'Sep',
        "Active User": 2000,
    },
    {
        name: 'Oct',
        "Active User": 5390,
    },
    {
        name: 'Nov',
        "Active User": 4000,
    },
    {
        name: 'Dec',
        "Active User": 4120,
    },
];

export const userRows = [{
        id: 1,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 2,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 3,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 4,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 5,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 6,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 7,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 8,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 9,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 10,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
];

export const productRows = [{
        id: 1,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 2,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 3,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 4,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 5,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 6,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 7,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 8,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 9,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 10,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
];
